### ISSUE TITLE
[Bug]: 程序出现错误，错误信息：list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by Solizaam** [ZianTT/BHYG#52]
### 描述这个Bug

程序出现错误，错误信息：list indices must be integers or slices, not str

### 复现步骤

在配置过程中遇到的问题

### 预期操作

请帮忙解决一下，谢谢

### 截图

<img width="852" alt="微信图片_20240223202322" src="https://github.com/ZianTT/BHYG/assets/159325096/248c69bf-9c58-45dd-9d7c-177e71b68188">

### 问题版本

main分支-Release

### 日志

```shell
2024-02-23 20:14:28.547 | DEBUG    | api:__init__:77 - 您的screen_id 和 sku_id 和 pay_money 分别为：162913
2024-02-23 20:14:28.618 | INFO     | api:__init__:91 - 本项目只能购买一人票
2024-02-23 20:14:29.423 | ERROR    | __main__:<module>:67 - 程序出现错误，错误信息：list indices must be integers or slices, not str
Traceback (most recent call last):

> File "main.py", line 60, in <module>

  File "api.py", line 99, in __init__

TypeError: list indices must be integers or slices, not str
2024-02-23 20:14:29.427 | CRITICAL | __main__:<module>:68 - 错误追踪ID(可提供给开发者)：6c438a1420aa48cc810c4d08197e97c5
2024-02-23 20:14:29.428 | INFO     | __main__:<module>:69 - 按回车将继续...
```

### 我是最新版本

- [X] 我确认这是该分支的最新版本且这是第一个针对该问题的Issue

**Comment by ZianTT** [comment]
你的选择票档好像有些问题，晚点我看看吧

**Comment by Solizaam** [comment]
好的，谢谢

**Comment by ZianTT** [comment]
我做了测试，并没有该项目ID，请检查是否正确

**Comment by Solizaam** [comment]
是票档id吗

**Comment by ZianTT** [comment]
> 是票档id吗

是你在会员购网页链接上看到的那个id，那个id不存在

**Comment by Solizaam** [comment]
https://mall.bilibili.com/neul-next/ticket/detail.html?&id=81820&from=pc_search&noTitleBar=1
这个是链接 是81820吧 我记得我输的是这个

**Comment by Solizaam** [comment]
我回去再试试看

**Comment by ZianTT** [comment]
稍等，是有点bug，我看看
